// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuimiJsNEScNV4932rcQgcJr5_A2nzYlo',
    appId: '1:228455474740:web:279335cfe1bf476cb28c61',
    messagingSenderId: '228455474740',
    projectId: 'app-viajeros-f3ca7',
    authDomain: 'app-viajeros-f3ca7.firebaseapp.com',
    storageBucket: 'app-viajeros-f3ca7.appspot.com',
    measurementId: 'G-22H8JYK85W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMwixChN7yVegSoi_S5GNin1msQ-bVGtc',
    appId: '1:228455474740:android:26a28e4927b1a044b28c61',
    messagingSenderId: '228455474740',
    projectId: 'app-viajeros-f3ca7',
    storageBucket: 'app-viajeros-f3ca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9_ULbEkc84wgzDuD1NE1PeH2W6wD18Fk',
    appId: '1:228455474740:ios:47bbd7187643a729b28c61',
    messagingSenderId: '228455474740',
    projectId: 'app-viajeros-f3ca7',
    storageBucket: 'app-viajeros-f3ca7.appspot.com',
    iosClientId: '228455474740-8m0upe9fvb2rlcpnkrbo3u0etgn6810k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptoyectoCiclo4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9_ULbEkc84wgzDuD1NE1PeH2W6wD18Fk',
    appId: '1:228455474740:ios:47bbd7187643a729b28c61',
    messagingSenderId: '228455474740',
    projectId: 'app-viajeros-f3ca7',
    storageBucket: 'app-viajeros-f3ca7.appspot.com',
    iosClientId: '228455474740-8m0upe9fvb2rlcpnkrbo3u0etgn6810k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptoyectoCiclo4',
  );
}
